--- #YAML:1.0
name:               File-Rsync-Mirror-Recent
version:            0.0.3
abstract:           ~
author:
    - Andreas König <andreas.koenig.7os6VVqR@franz.ak.mind.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    accessors:         0
    Data::Float:       0
    Data::Serializer:  0
    File::Basename:    0
    File::Path:        0
    File::Rsync:       0
    File::Temp:        0
    List::MoreUtils:   0
    List::Pairwise:    0
    Scalar::Util:      0
    Test::More:        0
    Time::HiRes:       0
    YAML::Syck:        0
provides:
    File::Rsync::Mirror::Recent:
        file:  lib/File/Rsync/Mirror/Recent.pm
        version:  0.0.3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
repository:         git://repo.or.cz/rersyncrecent.git
